CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=y
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=y
CONFIG_LV_Z_VDB_SIZE=64
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y